services:
  app:
    build: .
    container_name: fastapi_app

    ports:
      - "8000:8000"

    working_dir: /code

    volumes:
      - .:/code

    env_file:
      - .env

    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

    depends_on:
      - redis

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:7
    container_name: redis_db
    restart: always

    ports:
      - "6379:6379"

volumes:
  postgres_data:
