"""add last_quiz_attempt_at to users

Revision ID: 87e77ecd4e33
Revises: 73168aef36be
Create Date: 2026-06-10 11:10:59.589600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e77ecd4e33'
down_revision: Union[str, Sequence[str], None] = '73168aef36be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_quiz_attempt_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_quiz_attempt_at')
    # ### end Alembic commands ###
